- name: bigdata-bootstrap
  hosts: all
  roles:
  - role: ops
  - role: prerequisites
  - role: hdfs
    tags:
    - hdfs
  - role: zookeeper
    tags:
    - zookeeper
  - role: hbase
    tags:
    - hbase
