---
hadoop_bin_url: https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1.tar.gz
# hadoop-env.sh
hadoop_env_sh:
- {name: JAVA_HOME, value: /usr/lib/jvm/java-1.8.0}
- {name: HDFS_NAMENODE_USER, value: root}
- {name: HDFS_DATANODE_USER, value: root}
- {name: HDFS_SECONDARYNAMENODE_USER, value: root}
- {name: YARN_RESOURCEMANAGER_USER, value: root}
- {name: YARN_NODEMANAGER_USER, value: root}
